
services:
  # 1. Django Backend Service
  backend:
    build: ./Backend/erp_backend
    container_name: erp_django_backend
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    ports:
      - "8000:8000"

  # 2. React Frontend Service
  frontend:
    build: ./Front-end/myapp
    container_name: erp_react_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
