# Generated by Django 6.0.6 on 2026-06-23 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedGood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brandName', models.CharField(blank=True, max_length=255)),
                ('productId', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=50)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.brand')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('reorder', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contactPerson', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('totalPurchases', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lastPurchaseDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
