# Generated by Django 6.0.6 on 2026-06-23 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_brand_finishedgood_rawmaterial_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('monthlySalary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currentBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lastSettled', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paidTo', models.CharField(blank=True, max_length=255, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rawMaterialName', models.CharField(blank=True, max_length=255)),
                ('qtyPerUnit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.bom')),
                ('rawMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('brandName', models.CharField(blank=True, max_length=255)),
                ('productId', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=255)),
                ('qty', models.IntegerField(default=0)),
                ('totalRawConsumed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.brand')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employeeName', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=255)),
                ('brandName', models.CharField(blank=True, max_length=255)),
                ('productId', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=255)),
                ('qty', models.IntegerField(default=0)),
                ('unitPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.brand')),
            ],
        ),
    ]
