# Generated by Django 6.0.6 on 2026-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_bom_employee_expense_bomitem_productionbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgood',
            name='reorderLevel',
            field=models.IntegerField(default=500),
        ),
    ]
